name: Dart

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1.3

      - name: checkout
        run: |
          commits=${{ github.event.pull_request.commits }}
          if [[ -n "$commits" ]]; then
            # Prepare enough depth for diffs with master
            git fetch --depth="$(( commits + 1 ))"
          fi

      - name: Install dependencies
        run: dart pub get

      - name: Generate imports file for coverage
        run: dart ci/generate_coverage_helper.dart

      - name: Test
        run: dart test --coverage

      - name: Format
        run: dart format -l 200 .

      - name: Activate pull_request_coverage
        run: dart pub global activate pull_request_coverage

      - name: pull_request_coverage
        run: git diff origin/master | flutter pub run pull_request_coverage
